name: Docker Image Publish

on:
  push:
    branches:
    - e2e

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.SAMPLEAPP_ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.SAMPLEAPP_ACR_PASSWORD }}
        # Container registry server url
        login-server: x4utestcommonregistrydev.azurecr.io
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag x4utestcommonregistrydev.azurecr.io/aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag x4utestcommonregistrydev.azurecr.io/aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER x4utestcommonregistrydev.azurecr.io/aoai-chatgpt:latest;
        docker push x4utestcommonregistrydev.azurecr.io/aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push x4utestcommonregistrydev.azurecr.io/aoai-chatgpt:latest;
      
